package save

import (
	"bytes"
	"context"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"testing"

	"psql_crud/internal/storage"

	"github.com/go-chi/chi/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type MockURLSaver struct {
	id  int
	err error
}

func (m *MockURLSaver) SaveURL(ctx context.Context, urlToSave string, alias string) (int, error) {
	return m.id, m.err
}

type MockURLSaverWithCounter struct {
	saveFunc func(ctx context.Context, urlToSave string, alias string) (int, error)
}

func (m *MockURLSaverWithCounter) SaveURL(ctx context.Context, urlToSave string, alias string) (int, error) {
	return m.saveFunc(ctx, urlToSave, alias)
}

func createTestRequest(body []byte) *http.Request {
	req := httptest.NewRequest(http.MethodPost, "/url", bytes.NewBuffer(body))
	req = req.WithContext(context.WithValue(req.Context(), chi.RouteCtxKey, chi.NewRouteContext()))
	return req
}

func newTestLogger() *slog.Logger {
	return slog.New(slog.NewJSONHandler(io.Discard, nil))
}

func TestNew(t *testing.T) {
	tests := []struct {
		name           string
		body           string
		mockID         int
		mockErr        error
		expectedStatus int
		expectedAlias  string
		expectedError  string
	}{
		{
			name:           "success with custom alias",
			body:           `{"url":"https://example.com","alias":"myalias"}`,
			mockID:         1,
			mockErr:        nil,
			expectedStatus: http.StatusOK,
			expectedAlias:  "myalias",
		},
		{
			name:           "success with auto-generated alias",
			body:           `{"url":"https://example.com"}`,
			mockID:         1,
			mockErr:        nil,
			expectedStatus: http.StatusOK,
			expectedAlias:  "",
		},
		{
			name:           "URL without https protocol",
			body:           `{"url":"http://example.com","alias":"myalias"}`,
			mockID:         0,
			mockErr:        nil,
			expectedStatus: http.StatusOK,
			expectedError:  "URL must starts with 'https://'",
		},
		{
			name:           "invalid URL format",
			body:           `{"url":"not-a-url","alias":"myalias"}`,
			mockID:         0,
			mockErr:        nil,
			expectedStatus: http.StatusOK,
			expectedError:  "URL must starts with 'https://'",
		},
		{
			name:           "empty URL (required field)",
			body:           `{"url":"","alias":"myalias"}`,
			mockID:         0,
			mockErr:        nil,
			expectedStatus: http.StatusOK,
			expectedError:  "URL must starts with 'https://'",
		},
		{
			name:           "alias already exists (user-provided)",
			body:           `{"url":"https://example.com","alias":"existing"}`,
			mockID:         0,
			mockErr:        storage.ErrAliasExists,
			expectedStatus: http.StatusOK,
			expectedError:  "alias already exists",
		},
		{
			name:           "storage error",
			body:           `{"url":"https://example.com","alias":"myalias"}`,
			mockID:         0,
			mockErr:        errors.New("database error"),
			expectedStatus: http.StatusOK,
			expectedError:  "failed to save URL",
		},
		{
			name:           "max attempts reached for unique alias",
			body:           `{"url":"https://example.com"}`,
			mockID:         0,
			mockErr:        storage.ErrAliasExists,
			expectedStatus: http.StatusOK,
			expectedError:  "failed to generate unique alias",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mockSaver := &MockURLSaver{
				id:  tt.mockID,
				err: tt.mockErr,
			}
			logger := newTestLogger()
			handler := New(logger, mockSaver)

			req := createTestRequest([]byte(tt.body))
			w := httptest.NewRecorder()

			handler(w, req)

			if tt.expectedError != "" {
				assert.Equal(t, http.StatusOK, w.Code)
				assert.Contains(t, w.Body.String(), tt.expectedError)
			} else {
				assert.Equal(t, tt.expectedStatus, w.Code)
				if tt.expectedAlias != "" {
					assert.Contains(t, w.Body.String(), tt.expectedAlias)
				}
				assert.Contains(t, w.Body.String(), "OK")
			}
		})
	}
}

func TestNew_SuccessWithCustomAlias(t *testing.T) {
	mockSaver := &MockURLSaver{
		id:  123,
		err: nil,
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"https://example.com","alias":"myalias"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), `"alias":"myalias"`)
	assert.Contains(t, w.Body.String(), `"status":"OK"`)
}

func TestNew_SuccessWithAutoGeneratedAlias(t *testing.T) {
	mockSaver := &MockURLSaver{
		id:  123,
		err: nil,
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"https://example.com"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), `"status":"OK"`)
	
	assert.Contains(t, w.Body.String(), "alias")
}

func TestNew_URLWithoutHTTPS_ReturnsError(t *testing.T) {
	mockSaver := &MockURLSaver{}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"http://example.com","alias":"myalias"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "URL must starts with 'https://'")
}

func TestNew_InvalidURL_ReturnsValidationError(t *testing.T) {
	mockSaver := &MockURLSaver{}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"not-a-valid-url","alias":"myalias"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "URL must starts with 'https://'")
}

func TestNew_EmptyURL_ReturnsValidationError(t *testing.T) {
	mockSaver := &MockURLSaver{}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"","alias":"myalias"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "URL must starts with 'https://'")
}

func TestNew_AliasAlreadyExists_UserProvided_ReturnsError(t *testing.T) {
	mockSaver := &MockURLSaver{
		err: storage.ErrAliasExists,
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"https://example.com","alias":"existing"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "alias already exists")
}

func TestNew_AliasAlreadyExists_AutoGenerated_Retries(t *testing.T) {
	callCount := 0
	mockURLSaver := &MockURLSaverWithCounter{
		saveFunc: func(ctx context.Context, urlToSave string, alias string) (int, error) {
			callCount++
			if callCount <= 2 {
				return 0, storage.ErrAliasExists
			}
			return 123, nil
		},
	}
	logger := newTestLogger()
	handler := New(logger, mockURLSaver)

	body := []byte(`{"url":"https://example.com"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "OK")
	assert.Equal(t, 3, callCount, "SaveURL should be called 3 times (2 failures + 1 success)")
}

func TestNew_StorageError_ReturnsInternalError(t *testing.T) {
	mockSaver := &MockURLSaver{
		err: errors.New("database connection failed"),
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"https://example.com","alias":"myalias"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "failed to save URL")
}

func TestNew_MaxAttemptsReached_ReturnsError(t *testing.T) {
	mockSaver := &MockURLSaverWithCounter{
		saveFunc: func(ctx context.Context, urlToSave string, alias string) (int, error) {
			return 0, storage.ErrAliasExists
		},
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	body := []byte(`{"url":"https://example.com"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "failed to generate unique alias")
}

func TestNew_DecodeError_ReturnsError(t *testing.T) {
	mockSaver := &MockURLSaver{}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	// Invalid JSON body
	body := []byte(`{invalid json}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), "failed to decode request")
}

func TestNew_WithLongURL(t *testing.T) {
	mockSaver := &MockURLSaver{
		id:  1,
		err: nil,
	}
	logger := newTestLogger()
	handler := New(logger, mockSaver)

	longURL := "https://example.com/very/long/url/path/with/many/segments/and/query/parameters?param1=value1&param2=value2&param3=value3"
	body := []byte(`{"url":"` + longURL + `","alias":"longurl"}`)
	req := createTestRequest(body)
	w := httptest.NewRecorder()

	handler(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), `"status":"OK"`)
}

func TestResponseOK(t *testing.T) {
	w := httptest.NewRecorder()
	r := httptest.NewRequest(http.MethodGet, "/", nil)

	responseOK(w, r, "testalias")

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), `"status":"OK"`)
	assert.Contains(t, w.Body.String(), `"alias":"testalias"`)
}

func requireEqual(t *testing.T, expected, actual interface{}) {
	require.Equal(t, expected, actual)
}
